all: regex_test.pdf regex_fuzzer.pdf

regex_test.pdf:
	cat test-header.pdf regex_test.js test-footer.pdf > regex_test.pdf

regex_fuzzer.pdf:
	cat test-header.pdf regex_fuzzer.js test-footer.pdf > regex_fuzzer.pdf

clean:
	rm regex_test.pdf regex_fuzzer.pdf

